// 生成 Windows 兼容的 .bat 文件
// 纯 ASCII + CRLF (0x0D 0x0A)，无 BOM，零编码隐患

const fs = require('fs');
const path = require('path');

const outDir = path.resolve(__dirname, '../deploy/local-win');

function writeBat(filename, contentLines) {
  const crlf = '\r\n';
  const buf = Buffer.from(contentLines.join(crlf) + crlf, 'ascii');
  const outPath = path.join(outDir, filename);
  fs.writeFileSync(outPath, buf);
  console.log(`  OK: ${filename} (${buf.length} bytes, ASCII + CRLF)`);
}

// start.bat — 自动检测路径启动服务
writeBat('start.bat', [
  '@echo off',
  'set "CB=chcp 65001 >nul"',
  '%CB%',
  'title AI Novel Studio',
  'setlocal enabledelayedexpansion',
  '',
  'set "SCRIPT_DIR=%~dp0"',
  'set "SERVER_JS="',
  'set "WORK_DIR="',
  '',
  'if exist "%SCRIPT_DIR%server\\main.js" (',
  '    set "SERVER_JS=%SCRIPT_DIR%server\\main.js"',
  '    set "WORK_DIR=%SCRIPT_DIR%"',
  ')',
  '',
  'if not defined SERVER_JS (',
  '    for %%i in ("%SCRIPT_DIR%..") do set "PARENT=%%~fi"',
  '    if exist "!PARENT!\\apps\\server\\dist\\main.js" (',
  '        set "SERVER_JS=!PARENT!\\apps\\server\\dist\\main.js"',
  '        set "WORK_DIR=!PARENT!"',
  '    )',
  ')',
  '',
  'if not defined SERVER_JS (',
  '    echo [ERROR] Cannot find server/main.js.',
  '    echo Please run build.bat first, or run from project root.',
  '    pause',
  '    exit /b 1',
  ')',
  '',
  'cd /d "!WORK_DIR!"',
  '',
  'if not exist ".env" (',
  '    echo [INIT] Generating .env...',
  '    node -e "require(""crypto"").randomBytes(48).toString(""hex"")" > _jwt.tmp',
  '    set /p NS=<_jwt.tmp 2>nul',
  '    del _jwt.tmp 2>nul',
  '    (',
  '        echo APP_MODE=local',
  '        echo PORT=18765',
  '        echo DATABASE_URL=file:./data/novel.db',
  '        echo STORAGE_DRIVER=local',
  '        echo STORAGE_LOCAL_PATH=./data/uploads',
  '        echo QUEUE_DRIVER=sqlite',
  '        echo AUTH_MODE=local',
  '        echo JWT_SECRET=!NS!',
  '        echo JWT_EXPIRES_IN=7d',
  '        echo APP_SECRET=!NS!',
  '        echo KNOWLEDGE_PATH=./knowledge',
  '        echo KNOWLEDGE_RETRIEVAL_MODE=fts',
  '        echo LOG_LEVEL=info',
  '    ) ^> .env',
  '    echo [INIT] .env created.',
  ')',
  '',
  'if not exist "node_modules" (',
  '    echo [INIT] Installing dependencies...',
  '    call npm install --production',
  ')',
  '',
  'if not exist "node_modules\\.prisma\\client\\index.js" (',
  '    echo [INIT] Generating Prisma client...',
  '    if exist "prisma\\schema.prisma" if exist "node_modules\\prisma\\build\\index.js" node node_modules\\prisma\\build\\index.js generate --schema=prisma\\schema.prisma',
  ')',
  '',
  'if not exist "data" mkdir data 2>nul',
  'if not exist "data\\uploads" mkdir data\\uploads 2>nul',
  'if not exist "data\\backups" mkdir data\\backups 2>nul',
  '',
  'if exist "prisma\\schema.prisma" if exist "node_modules\\prisma\\build\\index.js" (',
  '    echo [INIT] Syncing database schema...',
  '    node node_modules\\prisma\\build\\index.js db push --accept-data-loss --schema=prisma\\schema.prisma --skip-generate >nul 2>&1',
  '    node node_modules\\prisma\\build\\index.js generate --schema=prisma\\schema.prisma >nul 2>&1',
  '    echo [INIT] Database schema synced.',
  ')',
  '',
  'echo.',
  'echo ========================================',
  'echo   AI Novel Studio v0.1.0',
  'echo ========================================',
  'echo.',
  'echo Working dir: !WORK_DIR!',
  'echo Entry: !SERVER_JS!',
  'echo.',
  '',
  'rem Node.js module lookup: try WORK_DIR first, then fallback to parent',
  'set "NODE_PATH=!WORK_DIR!\\node_modules"',
  'if not exist "!NODE_PATH!" (',
  '    for %%i in ("!WORK_DIR!..") do set "PARENT_MODULES=%%~fi\\node_modules"',
  '    if exist "!PARENT_MODULES!" set "NODE_PATH=!PARENT_MODULES!"',
  ')',
  '',
  'echo [START] Launching server...',
  'start "" "http://127.0.0.1:18765"',
  'node "!SERVER_JS!"',
  '',
  'echo.',
  'echo Server stopped.',
  'pause',
]);

// stop.bat — 查找端口停止
writeBat('stop.bat', [
  '@echo off',
  'chcp 65001 >nul',
  'title AI Novel Studio - Stop',
  '',
  'echo Stopping AI Novel Studio...',
  '',
  'set "FOUND_PID="',
  'for /f "tokens=5" %%a in (\'netstat -ano ^| findstr ":18765 " ^| findstr LISTENING\') do (',
  '    set "FOUND_PID=%%a"',
  ')',
  '',
  'if defined FOUND_PID (',
  '    echo Stopping PID: %FOUND_PID%',
  '    taskkill /F /PID %FOUND_PID% 2>nul',
  ') else (',
  '    echo No running service found.',
  ')',
  '',
  'timeout /t 2 >nul',
]);

// uninstall.bat
writeBat('uninstall.bat', [
  '@echo off',
  'chcp 65001 >nul',
  'title AI Novel Studio - Uninstall',
  '',
  'echo ========================================',
  'echo   Uninstall AI Novel Studio v0.1.0',
  'echo ========================================',
  'echo.',
  '',
  'echo [1/4] Stopping service...',
  'call "%~dp0stop.bat" >nul 2>&1',
  'echo   OK',
  '',
  'echo [2/4] Removing program files...',
  'set "INSTALL_DIR=%LOCALAPPDATA%\\AI-Novel-Studio"',
  'if exist "%INSTALL_DIR%" (',
  '    rmdir /S /Q "%INSTALL_DIR%" 2>nul',
  '    echo   Deleted: %INSTALL_DIR%',
  ') else (',
  '    echo   Not found.',
  ')',
  'echo   OK',
  '',
  'echo [3/4] Removing desktop shortcut...',
  'if exist "%USERPROFILE%\\Desktop\\AI Novel Studio.lnk" (',
  '    del /F /Q "%USERPROFILE%\\Desktop\\AI Novel Studio.lnk" 2>nul',
  ')',
  'echo   OK',
  '',
  'echo [4/4] Removing Start Menu items...',
  'if exist "%APPDATA%\\Microsoft\\Windows\\Start Menu\\Programs\\AI Novel Studio" (',
  '    rmdir /S /Q "%APPDATA%\\Microsoft\\Windows\\Start Menu\\Programs\\AI Novel Studio" 2>nul',
  ')',
  'echo   OK',
  '',
  'echo.',
  'echo Uninstall complete.',
  'pause',
]);

// build.bat — 构建发布包
writeBat('build.bat', [
  '@echo off',
  'chcp 65001 >nul',
  'title AI Novel Studio - Build',
  '',
  'echo ========================================',
  'echo   Building AI Novel Studio v0.1.0',
  'echo ========================================',
  'echo.',
  '',
  'set "ROOT_DIR=%~dp0..\\.."',
  'set "DIST_DIR=%ROOT_DIR%\\dist"',
  '',
  'echo [1/6] Installing dependencies...',
  'cd /d "%ROOT_DIR%"',
  'call pnpm install',
  'echo   OK',
  'echo.',
  '',
  'echo [2/6] Building packages...',
  'cd /d "%ROOT_DIR%"',
  'call pnpm build',
  'echo   OK',
  'echo.',
  '',
  'echo [3/6] Generating Prisma client...',
  'cd /d "%ROOT_DIR%"',
  'call pnpm db:generate',
  'echo   OK',
  'echo.',
  '',
  'echo [4/6] Creating dist directory...',
  'if exist "%DIST_DIR%" rmdir /S /Q "%DIST_DIR%"',
  'mkdir "%DIST_DIR%"',
  'mkdir "%DIST_DIR%\\server"',
  'mkdir "%DIST_DIR%\\web"',
  'mkdir "%DIST_DIR%\\prisma"',
  'mkdir "%DIST_DIR%\\data"',
  'mkdir "%DIST_DIR%\\data\\uploads"',
  'mkdir "%DIST_DIR%\\data\\backups"',
  'echo   OK',
  'echo.',
  '',
  'echo [5/6] Copying build artifacts...',
  'xcopy /E /I /Y "%ROOT_DIR%\\apps\\server\\dist\\*" "%DIST_DIR%\\server\\" >nul',
  'echo   - Server OK',
  'xcopy /E /I /Y "%ROOT_DIR%\\apps\\web\\dist\\*" "%DIST_DIR%\\web\\" >nul',
  'echo   - Web OK',
  '',
  'rem Copy workspace packages (fix main field to point to root index.js)',
  'mkdir "%DIST_DIR%\\node_modules\\@ai-novel" 2>nul',
  'for %%p in (ai-gateway seven-step-engine workflow-engine knowledge-base) do (',
  '    if exist "%ROOT_DIR%\\packages\\%%p\\dist" (',
  '        mkdir "%DIST_DIR%\\node_modules\\@ai-novel\\%%p" 2>nul',
  '        xcopy /E /I /Y "%ROOT_DIR%\\packages\\%%p\\dist\\*" "%DIST_DIR%\\node_modules\\@ai-novel\\%%p\\" >nul',
  '        echo {"main":"./index.js"} > "%DIST_DIR%\\node_modules\\@ai-novel\\%%p\\package.json"',
  '    )',
  ')',
  'echo   - Workspace packages OK',
  '',
  'rem Generate package.json for production dependencies',
  'cd /d "%DIST_DIR%"',
  'echo { > package.json',
  'echo   "name": "ai-novel-studio", >> package.json',
  'echo   "version": "1.4.8", >> package.json',
  'echo   "private": true, >> package.json',
  'echo   "scripts": { "start": "node server/main.js" }, >> package.json',
  'echo   "dependencies": { >> package.json',
  'echo     "@nestjs/common": "^11.0.0", >> package.json',
  'echo     "@nestjs/config": "^4.0.0", >> package.json',
  'echo     "@nestjs/core": "^11.0.0", >> package.json',
  'echo     "@nestjs/jwt": "^11.0.0", >> package.json',
  'echo     "@nestjs/passport": "^11.0.0", >> package.json',
  'echo     "@nestjs/platform-express": "^11.0.0", >> package.json',
  'echo     "@nestjs/swagger": "^11.0.0", >> package.json',
  'echo     "@prisma/client": "^6.0.0", >> package.json',
  'echo     "axios": "^1.6.0", >> package.json',
  'echo     "bcryptjs": "^2.4.3", >> package.json',
  'echo     "class-transformer": "^0.5.1", >> package.json',
  'echo     "class-validator": "^0.14.1", >> package.json',
  'echo     "passport": "^0.7.0", >> package.json',
  'echo     "passport-jwt": "^4.0.1", >> package.json',
  'echo     "prisma": "^6.0.0", >> package.json',
  'echo     "reflect-metadata": "^0.2.1", >> package.json',
  'echo     "rxjs": "^7.8.1", >> package.json',
  'echo     "swagger-ui-express": "^5.0.1" >> package.json',
  'echo   } >> package.json',
  'echo } >> package.json',
  '',
  'echo   Installing npm dependencies in dist...',
  'call npm install --production --legacy-peer-deps 2>nul',
  'if %errorLevel% neq 0 call npm install --production',
  'echo   - npm dependencies OK',
  '',
  'rem Re-copy workspace packages (npm install may have cleaned node_modules/@ai-novel)',
  'mkdir "%DIST_DIR%\\node_modules\\@ai-novel" 2>nul',
  'for %%p in (ai-gateway seven-step-engine workflow-engine knowledge-base) do (',
  '    if exist "%ROOT_DIR%\\packages\\%%p\\dist" (',
  '        mkdir "%DIST_DIR%\\node_modules\\@ai-novel\\%%p" 2>nul',
  '        xcopy /E /I /Y "%ROOT_DIR%\\packages\\%%p\\dist\\*" "%DIST_DIR%\\node_modules\\@ai-novel\\%%p\\" >nul',
  '        echo {"main":"./index.js"} > "%DIST_DIR%\\node_modules\\@ai-novel\\%%p\\package.json"',
  '    )',
  ')',
  'echo   - Workspace packages re-applied OK',
  '',
  'rem Generate Prisma client in dist',
  'echo   Generating Prisma client...',
  'if exist "prisma\\schema.prisma" if exist "node_modules\\prisma\\build\\index.js" node node_modules\\prisma\\build\\index.js generate --schema=prisma\\schema.prisma',
  'echo   - Prisma client OK',
  'copy /Y "%ROOT_DIR%\\apps\\server\\prisma\\schema.prisma" "%DIST_DIR%\\prisma\\" >nul',
  'echo   - Prisma OK',
  'if exist "%ROOT_DIR%\\resources\\rules" xcopy /E /I /Y "%ROOT_DIR%\\resources\\rules\\*" "%DIST_DIR%\\resources\\rules\\" >nul',
  'if exist "%ROOT_DIR%\\resources\\prompts" xcopy /E /I /Y "%ROOT_DIR%\\resources\\prompts\\*" "%DIST_DIR%\\resources\\prompts\\" >nul',
  'if exist "%ROOT_DIR%\\knowledge" xcopy /E /I /Y "%ROOT_DIR%\\knowledge\\*" "%DIST_DIR%\\knowledge\\" >nul',
  'echo   - Resources OK',
  'copy /Y "%~dp0start.bat" "%DIST_DIR%\\" >nul',
  'copy /Y "%~dp0stop.bat" "%DIST_DIR%\\" >nul',
  'echo   - Scripts OK',
  'echo   OK',
  'echo.',
  '',
  'echo [6/6] Generating .env template...',
  'cd /d "%DIST_DIR%"',
  'node -e "require(""crypto"").randomBytes(48).toString(""hex"")" > _jwt.tmp',
  'set /p JWT=<_jwt.tmp 2>nul',
  'del _jwt.tmp 2>nul',
  '( ^',
  'echo APP_MODE=local',
  'echo PORT=18765',
  'echo DATABASE_URL=file:./data/novel.db',
  'echo STORAGE_DRIVER=local',
  'echo STORAGE_LOCAL_PATH=./data/uploads',
  'echo QUEUE_DRIVER=sqlite',
  'echo AUTH_MODE=local',
  'echo JWT_SECRET=%JWT%',
  'echo JWT_EXPIRES_IN=7d',
  'echo APP_SECRET=%JWT%',
  'echo KNOWLEDGE_PATH=./knowledge',
  'echo KNOWLEDGE_RETRIEVAL_MODE=fts',
  'echo LOG_LEVEL=info',
  ') > .env',
  'cd /d "%ROOT_DIR%"',
  'echo   OK',
  'echo.',
  '',
  'echo ========================================',
  'echo   Build complete!',
  'echo ========================================',
  'echo.',
  'echo Output: %DIST_DIR%',
  'echo.',
  'echo To install:',
  'echo   1. cd dist',
  'echo   2. right-click install.bat ^> Run as Admin',
  'echo.',
  'pause',
]);

// install.bat — 安装到系统
writeBat('install.bat', [
  '@echo off',
  'chcp 65001 >nul',
  'title AI Novel Studio - Installer',
  '',
  'echo ========================================',
  'echo   AI Novel Studio v0.1.0 - Installer',
  'echo ========================================',
  'echo.',
  '',
  'net session >nul 2>&1',
  'if %errorLevel% neq 0 (',
  '    echo Please right-click and select "Run as administrator".',
  '    pause',
  '    exit /b 1',
  ')',
  '',
  'where node >nul 2>&1',
  'if %errorLevel% neq 0 (',
  '    echo Node.js not found. Please install Node.js 18+: https://nodejs.org/',
  '    pause',
  '    exit /b 1',
  ')',
  '',
  'for /f "tokens=*" %%i in (\'node -v\') do echo Node.js: %%i',
  'echo.',
  '',
  'set "INSTALL_DIR=%LOCALAPPDATA%\\AI-Novel-Studio"',
  'set "SOURCE_DIR=%~dp0"',
  '',
  'if not exist "%SOURCE_DIR%server\\main.js" (',
  '    echo [ERROR] Source files not found.',
  '    echo Please run build.bat first, then run install.bat from dist/.',
  '    pause',
  '    exit /b 1',
  ')',
  '',
  'echo Installing to: %INSTALL_DIR%',
  'echo.',
  '',
  'echo [1/5] Creating directories...',
  'if not exist "%INSTALL_DIR%" mkdir "%INSTALL_DIR%"',
  'if not exist "%INSTALL_DIR%\\data" mkdir "%INSTALL_DIR%\\data"',
  'if not exist "%INSTALL_DIR%\\data\\uploads" mkdir "%INSTALL_DIR%\\data\\uploads"',
  'if not exist "%INSTALL_DIR%\\data\\backups" mkdir "%INSTALL_DIR%\\data\\backups"',
  'echo   OK',
  '',
  'echo [2/5] Copying files...',
  'xcopy /E /I /Y "%SOURCE_DIR%server" "%INSTALL_DIR%\\server\\" >nul 2>&1',
  'xcopy /E /I /Y "%SOURCE_DIR%web" "%INSTALL_DIR%\\web\\" >nul 2>&1',
  'xcopy /E /I /Y "%SOURCE_DIR%prisma" "%INSTALL_DIR%\\prisma\\" >nul 2>&1',
  'copy /Y "%SOURCE_DIR%start.bat" "%INSTALL_DIR%\\" >nul 2>&1',
  'copy /Y "%SOURCE_DIR%stop.bat" "%INSTALL_DIR%\\" >nul 2>&1',
  'echo   OK',
  '',
  'echo [3/5] Installing dependencies...',
  'cd /d "%INSTALL_DIR%"',
  'echo { > package.json',
  'echo   "name": "ai-novel-studio", >> package.json',
  'echo   "version": "0.1.0", >> package.json',
  'echo   "private": true, >> package.json',
  'echo   "scripts": { "start": "node server/main.js" }, >> package.json',
  'echo   "dependencies": { >> package.json',
  'echo     "@nestjs/common": "^11.0.0", >> package.json',
  'echo     "@nestjs/config": "^4.0.0", >> package.json',
  'echo     "@nestjs/core": "^11.0.0", >> package.json',
  'echo     "@nestjs/jwt": "^11.0.0", >> package.json',
  'echo     "@nestjs/passport": "^11.0.0", >> package.json',
  'echo     "@nestjs/platform-express": "^11.0.0", >> package.json',
  'echo     "@nestjs/swagger": "^11.0.0", >> package.json',
  'echo     "@prisma/client": "^6.0.0", >> package.json',
  'echo     "axios": "^1.6.0", >> package.json',
  'echo     "bcryptjs": "^2.4.3", >> package.json',
  'echo     "class-transformer": "^0.5.1", >> package.json',
  'echo     "class-validator": "^0.14.1", >> package.json',
  'echo     "passport": "^0.7.0", >> package.json',
  'echo     "passport-jwt": "^4.0.1", >> package.json',
  'echo     "prisma": "^6.0.0", >> package.json',
  'echo     "reflect-metadata": "^0.2.1", >> package.json',
  'echo     "rxjs": "^7.8.1", >> package.json',
  'echo     "swagger-ui-express": "^5.0.1" >> package.json',
  'echo   } >> package.json',
  'echo } >> package.json',
  'call npm install --production --legacy-peer-deps 2>nul',
  'if %errorLevel% neq 0 call npm install --production',
  '',
  'echo   Generating Prisma client...',
  'if exist "prisma\\schema.prisma" if exist "node_modules\\prisma\\build\\index.js" node node_modules\\prisma\\build\\index.js generate --schema=prisma\\schema.prisma',
  'echo   OK',
  '',
  'echo   Copying workspace packages...',
  'mkdir "%INSTALL_DIR%\\node_modules\\@ai-novel" 2>nul',
  'xcopy /E /I /Y "%SOURCE_DIR%node_modules\\@ai-novel" "%INSTALL_DIR%\\node_modules\\@ai-novel\\" >nul 2>&1',
  'echo   OK',
  '',
  'echo [4/5] Generating config...',
  'node -e "require(""crypto"").randomBytes(48).toString(""hex"")" > _jwt.tmp',
  'set /p JWT=<_jwt.tmp 2>nul',
  'del _jwt.tmp 2>nul',
  'echo # AI Novel Studio - Env Config > .env',
  'echo APP_MODE=local >> .env',
  'echo PORT=18765 >> .env',
  'echo DATABASE_URL=file:./data/novel.db >> .env',
  'echo STORAGE_DRIVER=local >> .env',
  'echo STORAGE_LOCAL_PATH=./data/uploads >> .env',
  'echo QUEUE_DRIVER=sqlite >> .env',
  'echo AUTH_MODE=local >> .env',
  'echo JWT_SECRET=%JWT% >> .env',
  'echo JWT_EXPIRES_IN=7d >> .env',
  'echo APP_SECRET=%JWT% >> .env',
  'echo KNOWLEDGE_PATH=./knowledge >> .env',
  'echo KNOWLEDGE_RETRIEVAL_MODE=fts >> .env',
  'echo LOG_LEVEL=info >> .env',
  'echo   OK',
  '',
  'echo [5/5] Initializing database...',
  'if exist "node_modules\\.bin\\prisma.cmd" (',
  '    call node node_modules\\prisma\\build\\index.js db push --schema=prisma/schema.prisma --skip-generate 2>nul',
  '    echo   Database initialized.',
  ')',
  'echo   OK',
  '',
  'echo.',
  'echo ========================================',
  'echo   Installation complete!',
  'echo ========================================',
  'echo.',
  'echo Creating shortcuts...',
  '',
  'mshta "javascript:var sh=new ActiveXObject(\'WScript.Shell\');var lnk=sh.CreateShortcut(\'%USERPROFILE%\\Desktop\\AI Novel Studio.lnk\');lnk.TargetPath=\'%INSTALL_DIR%\\start.bat\';lnk.WorkingDirectory=\'%INSTALL_DIR%\';lnk.Description=\'AI Novel Studio v0.1.0\';lnk.Save();close();"',
  'echo   Desktop shortcut created.',
  '',
  'set "START_MENU=%APPDATA%\\Microsoft\\Windows\\Start Menu\\Programs"',
  'if not exist "%START_MENU%\\AI Novel Studio" mkdir "%START_MENU%\\AI Novel Studio"',
  'copy /Y "%INSTALL_DIR%\\start.bat" "%START_MENU%\\AI Novel Studio\\Start.bat" >nul',
  'copy /Y "%INSTALL_DIR%\\stop.bat" "%START_MENU%\\AI Novel Studio\\Stop.bat" >nul',
  'echo   Start Menu items created.',
  '',
  'echo.',
  'echo Installed: %INSTALL_DIR%',
  'echo.',
  'echo To start: double-click desktop "AI Novel Studio" shortcut.',
  'echo.',
  'pause',
]);

console.log('\nAll bat files written successfully.');
console.log(`Location: ${outDir}`);
